server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/paymentdb
    username: root
    password: password123
    driverClassName: com.mysql.jdbc.Driver
  jpa :
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: ConfigServer:https://localhost:9296
