server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB HOST:localhost}:3306/orderdb
    username: root
    password: password123
    driverClassName: com.mysql.jdbc.Driver
  jpa :
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: ConfigServer:https://localhost:9296


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

